server:
  port: 8082

spring:
  application:
    name: account-service
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:accountdb}
    username: ${DB_USER:bank}
    password: ${DB_PASS:bank}
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: update

app:
  jwt:
    secret: "QzDA+CdJtCsXPG+YO/9y/JluYMxrrsDeJYGrpA6gPhk="
