server:
  port: 8085

spring:
  application:
    name: analytics-service
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:analyticsdb}
    username: ${DB_USER:bank}
    password: ${DB_PASS:bank}
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: false

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:kafka:9092}
    consumer:
      group-id: analytics-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
