CREATE DATABASE IF NOT EXISTS authdb;
CREATE DATABASE IF NOT EXISTS accountdb;
CREATE DATABASE IF NOT EXISTS ledgerdb;
CREATE DATABASE IF NOT EXISTS transferdb;
CREATE DATABASE IF NOT EXISTS statementdb;
CREATE DATABASE IF NOT EXISTS analyticsdb;
CREATE DATABASE IF NOT EXISTS auditdb;

GRANT ALL PRIVILEGES ON authdb.* TO 'bank'@'%';
GRANT ALL PRIVILEGES ON accountdb.* TO 'bank'@'%';
GRANT ALL PRIVILEGES ON ledgerdb.* TO 'bank'@'%';
GRANT ALL PRIVILEGES ON transferdb.* TO 'bank'@'%';
GRANT ALL PRIVILEGES ON statementdb.* TO 'bank'@'%';
GRANT ALL PRIVILEGES ON analyticsdb.* TO 'bank'@'%';
GRANT ALL PRIVILEGES ON auditdb.* TO 'bank'@'%';
FLUSH PRIVILEGES;
